language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
os:
    - linux
    - osx
before_script:
    - |
      (rustup component add rustfmt-preview || true) &&
      (rustup component add clippy-preview || true)

script:
    - |
      export PATH="$PATH":~/.cargo/bin &&
      export RUST_BACKTRACE=1 &&
      export CARGO_INCREMENTAL=1 &&
      cargo build &&
      cargo test &&
      cargo doc --no-deps &&
      cargo clippy -- --deny clippy::all --deny warnings &&
      cargo fmt -- --check

matrix:
    allow_failures:
        - rust: nightly
